[package]
name = "calr"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term.workspace = true
anyhow.workspace = true
chrono = "0.4.34"
clap.workspace = true
itertools = "0.12.1"

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
pretty_assertions.workspace = true
