[package]
name = "catr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "2.33"

[dev-dependencies]
anyhow = "1.0.100"
pretty_assertions = "1.4.1"
assert_cmd = "2"
predicates = "2"
rand = "0.8"
